# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]
alternating = [false]
border = [false]

[grid]
size = ["0"]
coordinates = [false]

[crosshair]
length = ["40vmin"]
color = ["#00D9FF"]
stroke = ["3px"]

[circle]
stroke = ["0"]
color = ["#00000000"]

[labeled-edges]
thickness = ["0"]
side = []

[text]
text = [""]

[logo]
source = [""]

[render]
no-assignment = true
no-discovery = true
output = ""

[[output]]
target = 0
