# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]

[grid]
size = ["0"]

[crosshair]
length = ["40vmin"]
color = ["#00D9FF"]
stroke = ["3px"]

[circle]
color = ["#00000000"]

[labeled-edges]
thickness = ["0"]
side = []

[text]
format = [""]

[logo]
source = [""]

########### Everything from here ownwards is for sample-building purposes. 
########### Remove this is you're copying this sample to a production-ready config file.
[render]
no-assignment = true
no-discovery = true

########### Everything from here ownwards is for sample-building purposes. 
########### Remove this is you're copying this sample to a production-ready config file.
[[output]]
target = 0
