# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]

[grid]
size = ["64px"]
odd-color = ["#000"]
even-color = ["#8d0000"]
coordinates = [true]

[circle]
color = ["#00000000"]

[crosshair]
stroke = ["0"]
color = ["#00000000"]

[labeled-edges]
side = []

[text]
format = [""]

[logo]
source = [""]

########### Everything from here ownwards is for sample-building purposes. 
########### Remove this is you're copying this sample to a production-ready config file.
[render]
no-assignment = true
no-discovery = true

########### Everything from here ownwards is for sample-building purposes. 
########### Remove this is you're copying this sample to a production-ready config file.
[[output]]
target = 0
