# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]
alternating = [false]
border = [false]

[grid]
size = ["64px"]
odd-color = ["#000"]
even-color = ["#8d0000"]
stroke = ["0"]
coordinates = [true]

[circle]
stroke = ["0"]
color = ["#00000000"]

[crosshair]
stroke = ["0"]
color = ["#00000000"]

[labeled-edges]
side = []

[text]
text = [""]

[logo]
source = [""]

[render]
no-assignment = true
no-discovery = true
output = ""

[[output]]
target = 0

[output.hardware_output]
index = 0
desktopX = 0
desktopY = 0
widthPx = 640
heightPx = 480
dpiX = 96
dpiY = 96
rotation = 0
adapterName = "FIXED"
friendlyName = "Grid"
