# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]

[grid]
size = ["0"]

[labeled-edges]
text-size = ["14px"]
tail-length = ["20px"]
thickness = ["4px"]
head-scale = [1.2]
scope = ["Output"]
side = ["TL", "T", "TR", "R", "BR", "B", "BL", "L"]

[circle]
color = ["#00000000"]

[crosshair]
stroke = ["0"]
color = ["#00000000"]

[text]
text = [""]

[logo]
source = [""]

[render]
no-assignment = true
no-discovery = true

[[output]]
target = 0