# $schema: https://raw.githubusercontent.com/gameshowpro/BgRaster/refs/heads/main/docs/schemas/bgraster-config.schema.json

[background]
color = ["#000000"]
alternating = [false]
border = [false]

[grid]
size = ["0"]
coordinates = [false]

[text]
text = ["BgRaster", "Text + Logo", "640x480"]
size = ["8vh", "4vh", "4vh"]
color = ["#FFFFFF", "#a0a0a0", "#FFFFFF"]
x = ["50vw"]
y = ["70vh"]

[logo]
source = ["images/logo.png"]
x = ["50vw"]
y = ["45vh"]
width = ["40vw"]
height = ["25vh"]
opacity = [1]

[circle]
stroke = ["0"]
color = ["#00000000"]

[crosshair]
stroke = ["0"]
color = ["#00000000"]

[labeled-edges]
thickness = ["0"]
side = []

[render]
no-assignment = true
no-discovery = true
output = ""

[[output]]
target = 0

[output.hardware_output]
index = 0
desktopX = 0
desktopY = 0
widthPx = 640
heightPx = 480
dpiX = 96
dpiY = 96
rotation = 0
adapterName = "FIXED"
friendlyName = "Text and Logo"
