<#
.SYNOPSIS
    Generates a C# static class with simulated network adapter data.
.DESCRIPTION
    Collects real network adapter and IP address information from the local
    Windows machine and emits a C# source file that BgRaster compiles
    as part of the project. When [render].simulate-network = true, the
    NetworkSimulator returns this baked-in data instead of querying live
    interfaces.
    Run this script once and commit the output; it is not part of the build.
.PARAMETER OutputPath
    Path to write the generated C# file. Defaults to
    src/Network/NetworkSimulatorData.g.cs relative to the repo root.
.EXAMPLE
    pwsh scripts/generate-network-simulator.ps1
#>

param(
    [string]$OutputPath = $null
)

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir '..')
if (-not $OutputPath) {
    $OutputPath = Join-Path $RepoRoot 'src' 'Network' 'NetworkSimulatorData.g.cs'
}

Write-Host "Collecting network adapter data..." -ForegroundColor Cyan

$adapters = @()
$netAdapters = Get-NetAdapter -ErrorAction SilentlyContinue | Where-Object { $_.Status -ne 'Disconnected' }

if (-not $netAdapters) {
    Write-Warning "No active network adapters found. Generating empty simulator data."
    $netAdapters = @()
}

foreach ($adapter in $netAdapters) {
    $ips = @()
    $ipConfigs = Get-NetIPAddress -InterfaceIndex $adapter.InterfaceIndex -AddressFamily IPv4,IPv6 -ErrorAction SilentlyContinue |
        Where-Object { $_.PrefixOrigin -ne 'WellKnown' -and $_.SuffixOrigin -ne 'LinkLayerAddress' }

    foreach ($ip in $ipConfigs) {
        $origin = if ($ip.PrefixOrigin -eq $ip.SuffixOrigin) {
            $ip.PrefixOrigin.ToString()
        } else {
            "$($ip.PrefixOrigin)-$($ip.SuffixOrigin)"
        }
        $ips += @{
            Address  = $ip.IPAddress
            CidrBits = $ip.PrefixLength
            Origin   = $origin
        }
    }

    $ianaType = switch -Wildcard ($adapter.MediaType -or '') {
        '802.3'          { 6 }
        '802.11*'        { 71 }
        'Native 802.11*' { 71 }
        'Wireless*'      { 71 }
        'Tunnel'         { 131 }
        default          { 6 }
    }

    $speed = if ($adapter.LinkSpeed -and $adapter.LinkSpeed -match '^(\d+(?:\.\d+)?)\s*(\w+)') {
        $value = [double]$Matches[1]
        switch ($Matches[2]) {
            'Gbps' { [long]($value * 1000000000) }
            'Mbps' { [long]($value * 1000000) }
            'Kbps' { [long]($value * 1000) }
            'bps'  { [long]$value }
            default { [long]$value }
        }
    } else { -1L }

    $adapters += @{
        Name        = $adapter.Name
        Description = $adapter.InterfaceDescription
        Id          = $adapter.InterfaceGuid.ToString()
        IanaType    = $ianaType
        Status      = if ($adapter.Status -eq 'Up') { 'Up' } else { 'Down' }
        Speed       = $speed
        MacAddress  = ($adapter.MacAddress -replace '-', ':').ToUpper()
        Ips         = $ips
    }
}

$totalIps = ($adapters | ForEach-Object { $_.Ips.Count } | Measure-Object -Sum).Sum
Write-Host "Found $($adapters.Count) adapter(s) with $totalIps IP(s)." -ForegroundColor Green

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine(@'
// <auto-generated />
// Generated by scripts/generate-network-simulator.ps1
// Run this script on the development machine to update simulated network data.

using System.Collections.Immutable;

namespace GameshowPro.BgRaster.Network;

static class NetworkSimulatorData
{
    internal static ImmutableArray<AdapterInfo> Adapters { get; } =
        ImmutableArray.Create(
'@.TrimEnd())

for ($i = 0; $i -lt $adapters.Count; $i++) {
    $a = $adapters[$i]
    $comma = if ($i -lt $adapters.Count - 1) { ',' } else { '' }
    $name = $a.Name -replace '"', '\"'
    $desc = $a.Description -replace '"', '\"'

    [void]$sb.AppendLine("            new AdapterInfo")
    [void]$sb.AppendLine("            {")
    [void]$sb.AppendLine("                Name = `"$name`",")
    [void]$sb.AppendLine("                Description = `"$desc`",")
    [void]$sb.AppendLine("                Id = `"$($a.Id)`",")
    [void]$sb.AppendLine("                Type = GetType($($a.IanaType)),")
    [void]$sb.AppendLine("                TypeLong = GetTypeLong($($a.IanaType)),")
    [void]$sb.AppendLine("                Status = `"$($a.Status)`",")
    [void]$sb.AppendLine("                Speed = FormatSpeed($($a.Speed)L),")
    [void]$sb.AppendLine("                MacAddress = `"$($a.MacAddress)`",")
    [void]$sb.Append("                IpAddresses = ")

    $ips = $a.Ips
    if ($ips.Count -eq 0) {
        [void]$sb.AppendLine("ImmutableArray<AdapterIpAddress>.Empty$comma")
    } else {
        if ($ips.Count -eq 1) {
            [void]$sb.AppendLine("ImmutableArray.Create(")
            $ip = $ips[0]
            [void]$sb.AppendLine("                    new AdapterIpAddress")
            [void]$sb.AppendLine("                    {")
            [void]$sb.AppendLine("                        Address = `"$($ip.Address)`",")
            [void]$sb.AppendLine("                        CidrBits = $($ip.CidrBits),")
            [void]$sb.AppendLine("                        Origin = `"$($ip.Origin)`",")
            [void]$sb.AppendLine("                    }")
            [void]$sb.AppendLine("                ),")
        } else {
            [void]$sb.AppendLine("ImmutableArray.Create(")
            for ($j = 0; $j -lt $ips.Count; $j++) {
                $ip = $ips[$j]
                $ipComma = if ($j -lt $ips.Count - 1) { ',' } else { '' }
                [void]$sb.AppendLine("                    new AdapterIpAddress")
                [void]$sb.AppendLine("                    {")
                [void]$sb.AppendLine("                        Address = `"$($ip.Address)`",")
                [void]$sb.AppendLine("                        CidrBits = $($ip.CidrBits),")
                [void]$sb.AppendLine("                        Origin = `"$($ip.Origin)`",")
                [void]$sb.AppendLine("                    }$ipComma")
            }
            [void]$sb.AppendLine("                ),")
        }
    }
    [void]$sb.AppendLine("            }$comma")
}

[void]$sb.AppendLine(@'
        );

    private static string GetType(int ianaId) => NetworkCollector.IanaIfTypes.TryGetValue(ianaId, out var names) ? names.Short : ianaId.ToString();
    private static string GetTypeLong(int ianaId) => NetworkCollector.IanaIfTypes.TryGetValue(ianaId, out var names) ? names.Long : ianaId.ToString();
    private static string FormatSpeed(long bitsPerSecond)
    {
        if (bitsPerSecond <= 0) return "N/A";
        string[] units = { "b/s", "kb/s", "Mb/s", "Gb/s", "Tb/s" };
        double value = bitsPerSecond;
        int unitIdx = 0;
        while (value >= 1000 && unitIdx < units.Length - 1) { value /= 1000; unitIdx++; }
        return $"{value:0.#}{units[unitIdx]}";
    }
}
'@.TrimEnd())

$parent = Split-Path -Parent $OutputPath
if (-not (Test-Path $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}

$sb.ToString() | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "Generated: $OutputPath" -ForegroundColor Green