// SPDX-License-Identifier: MIT
// Copyright © 2026 Barjonas LLC

global using System;
global using System.Collections.Frozen;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.CommandLine;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Threading.Tasks;
global using GameshowPro.BgRaster.Configuration;
global using GameshowPro.BgRaster.Discovery;
global using GameshowPro.BgRaster.FileLifecycle;
global using GameshowPro.BgRaster.Hashing;
global using GameshowPro.BgRaster.Logging;
global using GameshowPro.BgRaster.Models;
global using GameshowPro.BgRaster.Network;
global using GameshowPro.BgRaster.Parsing;
global using GameshowPro.BgRaster.Rendering;
global using GameshowPro.BgRaster.Rendering.Layers;
global using GameshowPro.BgRaster.Resolution;
global using GameshowPro.BgRaster.StateCache;
global using GameshowPro.BgRaster.Wallpaper;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Console;
global using SkiaSharp;
global using Svg.Skia;
global using Tomlyn;
global using Tomlyn.Model;
