// SPDX-License-Identifier: MIT
// Copyright © 2026 Barjonas LLC

namespace GameshowPro.BgRaster.Network;

internal static class NetworkSimulator
{
    /// <summary>
    /// Returns simulated adapter data when [render].simulate-network is true.
    /// The data is generated by scripts/generate-network-simulator.ps1.
    /// </summary>
    internal static ImmutableArray<AdapterInfo> GetAdapters() => NetworkSimulatorData.Adapters;
}