// <auto-generated />
// Generated by scripts/generate-network-simulator.ps1
// Run this script on the development machine to update simulated network data.

using System.Collections.Immutable;

namespace GameshowPro.BgRaster.Network;

static class NetworkSimulatorData
{
    internal static ImmutableArray<AdapterInfo> Adapters { get; } =
        ImmutableArray.Create(
            new AdapterInfo
            {
                Name = "ST2110 Core Network A",
                Description = "Mellanox ConnectX-5 25GbE Adapter",
                Id = "{B8D3F6A1-4C2E-4F7A-9B1D-6E8C5A3F2D07}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(25000000000L),
                MacAddress = "0C:42:A1:B8:D3:F6",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "10.211.30.11",
                        CidrBits = 24,
                        Origin = "Dhcp",
                    },
                    new AdapterIpAddress
                    {
                        Address = "fe80::e42:a1ff:feb8:d3f6",
                        CidrBits = 64,
                        Origin = "WellKnown",
                    },
                    new AdapterIpAddress
                    {
                        Address = "2001:db8:211:30::11",
                        CidrBits = 64,
                        Origin = "Dhcp",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "ST2110 Core Network B",
                Description = "Mellanox ConnectX-5 25GbE Adapter #2",
                Id = "{C4E7A2F9-8D1B-4C5E-6A7F-3B0D9E2C1A58}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(25000000000L),
                MacAddress = "0C:42:A1:C4:E7:A2",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "10.211.30.12",
                        CidrBits = 24,
                        Origin = "Dhcp",
                    },
                    new AdapterIpAddress
                    {
                        Address = "fe80::e42:a1ff:fec4:e7a2",
                        CidrBits = 64,
                        Origin = "WellKnown",
                    },
                    new AdapterIpAddress
                    {
                        Address = "2001:db8:211:30::12",
                        CidrBits = 64,
                        Origin = "Dhcp",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "Dante network A",
                Description = "Intel I350 Gigabit Network Connection",
                Id = "{D1A5B3C7-4F2E-4A8D-9C6B-7E1F0D3A5B29}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(1000000000L),
                MacAddress = "A4:BF:01:D1:A5:B3",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "192.168.100.11",
                        CidrBits = 24,
                        Origin = "Manual",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "Dante network B",
                Description = "Intel I350 Gigabit Network Connection #2",
                Id = "{E3B7C5D9-6A1F-4B3E-8C7D-2F5A0E1B4C36}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(1000000000L),
                MacAddress = "A4:BF:01:E3:B7:C5",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "192.168.100.12",
                        CidrBits = 24,
                        Origin = "Manual",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "ZeroTier One [a1b2c3d4e5f6g7h8]",
                Description = "ZeroTier Virtual Port",
                Id = "{F7C2D4E6-8B0A-4C1D-9E5F-3A7B6D2C1E04}",
                Type = GetType(53),
                TypeLong = GetTypeLong(53),
                Status = "Up",
                Speed = FormatSpeed(100000000L),
                MacAddress = "FE:91:2D:B4:7A:3C",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "10.147.20.7",
                        CidrBits = 24,
                        Origin = "Manual",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "vEthernet (Default Switch)",
                Description = "Hyper-V Virtual Ethernet Adapter",
                Id = "{A9F1B3D5-7C2E-4A6F-8B1D-0E3C5F7A2B4D}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(10000000000L),
                MacAddress = "00:15:5D:3C:8A:6F",
                IpAddresses = ImmutableArray.Create(
                    new AdapterIpAddress
                    {
                        Address = "172.25.176.1",
                        CidrBits = 20,
                        Origin = "Manual",
                    }
                ),
            },
            new AdapterInfo
            {
                Name = "Local Area Connection 2",
                Description = "OpenVPN Data Channel Offload for RandoVPN",
                Id = "{B4D6E8A0-2C4E-4F6A-8D1B-5F7C9E3A1B2C}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Down",
                Speed = FormatSpeed(100000000L),
                MacAddress = "",
                IpAddresses = ImmutableArray<AdapterIpAddress>.Empty,
            },
            new AdapterInfo
            {
                Name = "vEthernet (FSE HostVnic)",
                Description = "Hyper-V Virtual Ethernet Container Adapter",
                Id = "{6C8D0E2F-4A5B-4C7D-9E1F-3A2B5C8D7E6F}",
                Type = GetType(6),
                TypeLong = GetTypeLong(6),
                Status = "Up",
                Speed = FormatSpeed(10000000000L),
                MacAddress = "00:15:5D:7F:2B:4E",
                IpAddresses = ImmutableArray<AdapterIpAddress>.Empty
            }
        );

    private static string GetType(int ianaId) => NetworkCollector.s_ianaIfTypes.TryGetValue(ianaId, out var names) ? names.Short : ianaId.ToString();
    private static string GetTypeLong(int ianaId) => NetworkCollector.s_ianaIfTypes.TryGetValue(ianaId, out var names) ? names.Long : ianaId.ToString();
    private static string FormatSpeed(long bitsPerSecond)
    {
        if (bitsPerSecond <= 0) return "N/A";
        string[] units = { "b/s", "kb/s", "Mb/s", "Gb/s", "Tb/s" };
        double value = bitsPerSecond;
        int unitIdx = 0;
        while (value >= 1000 && unitIdx < units.Length - 1) { value /= 1000; unitIdx++; }
        return $"{value:0.#}{units[unitIdx]}";
    }
}